---
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: bug
assignees: PranavPurwar
---

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - SNAPSHOT
        - 1.0.0 (Default)
        - 0.0.5
        - 0.0.4
        - 0.0.3
        - 0.0.2
        - 0.0.1
    validations:
      required: true
  - type: dropdown
    id: android
    attributes:
      label: What android version are you using?
      options:
        - Android 13
        - Android 12
        - Android 11
        - Android 10
        - Android 9
        - Android 8
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true